"""Regression tests for the `enforcement_mode` boot guard (WI-4) and the
cost-governance surface (WI-5).

These sit alongside the existing suite; they do not replace it.
"""

from __future__ import annotations

import logging

import pytest

from iaiso.audit import MemorySink, NullSink
from iaiso.core import (
    ENFORCEMENT_PERMISSIVE,
    ENFORCEMENT_STRICT,
    PressureConfig,
    PressureEngine,
    StrictModeError,
)
from iaiso.core.engine import Lifecycle, StepInput, StepOutcome


def calibrated(**overrides) -> PressureConfig:
    """A config that has been moved off library defaults."""
    base = dict(token_coefficient=0.011)
    base.update(overrides)
    return PressureConfig(**base)


def scripted(values):
    it = iter(values)
    last = [0.0]

    def clock():
        try:
            last[0] = next(it)
        except StopIteration:
            pass
        return last[0]

    return clock


# --------------------------------------------------------------------------
# WI-4 — boot guard
# --------------------------------------------------------------------------

def test_strict_refuses_null_sink():
    with pytest.raises(StrictModeError) as exc:
        PressureEngine(calibrated(), execution_id="t",
                       audit_sink=NullSink(),
                       enforcement_mode=ENFORCEMENT_STRICT)
    assert "NullSink" in str(exc.value)


def test_strict_refuses_missing_sink():
    # Omitting the sink entirely is the same degraded condition as passing
    # NullSink explicitly — it must not be a way around the guard.
    with pytest.raises(StrictModeError):
        PressureEngine(calibrated(), execution_id="t",
                       enforcement_mode=ENFORCEMENT_STRICT)


def test_strict_refuses_post_release_lock_disabled():
    cfg = calibrated(post_release_lock=False)
    with pytest.raises(StrictModeError) as exc:
        PressureEngine(cfg, execution_id="t", audit_sink=MemorySink(),
                       enforcement_mode=ENFORCEMENT_STRICT)
    assert "post_release_lock" in str(exc.value)


def test_strict_refuses_uncalibrated_defaults():
    with pytest.raises(StrictModeError) as exc:
        PressureEngine(PressureConfig(), execution_id="t",
                       audit_sink=MemorySink(),
                       enforcement_mode=ENFORCEMENT_STRICT)
    assert "calibrat" in str(exc.value)


def test_strict_accepts_defaults_with_calibration_artifact():
    engine = PressureEngine(PressureConfig(), execution_id="t",
                            audit_sink=MemorySink(),
                            enforcement_mode=ENFORCEMENT_STRICT,
                            calibration_artifact="calibration/2026-07-01.json")
    assert engine.enforcement_mode == ENFORCEMENT_STRICT


def test_strict_refuses_autogenerated_hs256_key():
    with pytest.raises(StrictModeError) as exc:
        PressureEngine(calibrated(), execution_id="t", audit_sink=MemorySink(),
                       enforcement_mode=ENFORCEMENT_STRICT,
                       consent_algorithm="HS256",
                       consent_key_auto_generated=True)
    assert "HS256" in str(exc.value)


def test_strict_accepts_a_sound_config():
    engine = PressureEngine(calibrated(), execution_id="t",
                            audit_sink=MemorySink(),
                            enforcement_mode=ENFORCEMENT_STRICT)
    assert engine.enforcement_mode == ENFORCEMENT_STRICT


def test_permissive_is_the_default_and_proceeds():
    engine = PressureEngine(PressureConfig(), execution_id="t")
    assert engine.enforcement_mode == ENFORCEMENT_PERMISSIVE


def test_permissive_warns_but_does_not_raise(caplog):
    import iaiso.core.engine as eng
    eng._warned.clear()
    with caplog.at_level(logging.WARNING, logger="iaiso"):
        PressureEngine(PressureConfig(), execution_id="t", audit_sink=NullSink())
    assert any("NullSink" in r.getMessage() for r in caplog.records)


def test_unknown_enforcement_mode_is_a_config_error():
    with pytest.raises(ValueError, match="enforcement_mode"):
        PressureEngine(calibrated(), execution_id="t", audit_sink=MemorySink(),
                       enforcement_mode="advisory")


def test_strict_refusal_leaves_nothing_constructed():
    # A half-built engine that emitted engine.init before refusing would be a
    # lie in the audit log.
    sink = MemorySink()
    with pytest.raises(StrictModeError):
        PressureEngine(PressureConfig(post_release_lock=False),
                       execution_id="t", audit_sink=sink,
                       enforcement_mode=ENFORCEMENT_STRICT)
    assert len(sink.events) == 0


# --------------------------------------------------------------------------
# WI-5 — cost governance
# --------------------------------------------------------------------------

def cost_config(**overrides) -> PressureConfig:
    base = dict(dissipation_per_step=0.0,
                model_costs={"frontier": 15.0, "small": 0.5})
    base.update(overrides)
    return PressureConfig(**base)


def test_spend_is_tracked_and_emitted():
    sink = MemorySink()
    engine = PressureEngine(cost_config(), execution_id="t", audit_sink=sink,
                            clock=scripted([0.0, 1.0, 2.0]))
    engine.step(StepInput(tokens=100_000, model="frontier"))
    assert engine.spend_usd == pytest.approx(1.5)

    steps = [e for e in sink.events if e.kind == "engine.step"]
    assert steps and "spend_usd" in steps[0].data


def test_spend_field_absent_without_model_costs():
    # Existing consumers of the frozen 1.0 envelope must not see a new key.
    sink = MemorySink()
    engine = PressureEngine(PressureConfig(dissipation_per_step=0.0),
                            execution_id="t", audit_sink=sink,
                            clock=scripted([0.0, 1.0]))
    engine.step(StepInput(tokens=1000))
    steps = [e for e in sink.events if e.kind == "engine.step"]
    assert steps and "spend_usd" not in steps[0].data


def test_unknown_model_costs_nothing():
    engine = PressureEngine(cost_config(), execution_id="t",
                            audit_sink=MemorySink(), clock=scripted([0.0, 1.0]))
    engine.step(StepInput(tokens=1_000_000, model="unpriced"))
    assert engine.spend_usd == 0.0


def test_budget_exceeded_reuses_the_lock_path():
    sink = MemorySink()
    engine = PressureEngine(cost_config(budget_usd=1.0), execution_id="t",
                            audit_sink=sink, clock=scripted([0.0, 1.0, 2.0]))
    outcome = engine.step(StepInput(tokens=100_000, model="frontier"))

    assert outcome is StepOutcome.LOCKED
    assert engine.lifecycle is Lifecycle.LOCKED

    locked = [e for e in sink.events if e.kind == "engine.locked"]
    assert locked and locked[0].data["reason"] == "budget_exceeded"

    # No new lifecycle state was invented.
    assert {e.kind for e in sink.events} <= {
        "engine.init", "engine.step", "engine.locked",
        "engine.release", "engine.reset", "engine.step.rejected",
    }


def test_budget_locked_engine_rejects_further_steps():
    engine = PressureEngine(cost_config(budget_usd=1.0), execution_id="t",
                            audit_sink=MemorySink(),
                            clock=scripted([0.0, 1.0, 2.0, 3.0]))
    engine.step(StepInput(tokens=100_000, model="frontier"))
    assert engine.step(StepInput(tokens=1)) is StepOutcome.LOCKED


def test_reset_clears_spend():
    engine = PressureEngine(cost_config(), execution_id="t",
                            audit_sink=MemorySink(),
                            clock=scripted([0.0, 1.0, 2.0]))
    engine.step(StepInput(tokens=100_000, model="frontier"))
    assert engine.spend_usd > 0
    engine.reset()
    assert engine.spend_usd == 0.0


def test_negative_budget_is_a_config_error():
    with pytest.raises(ValueError, match="budget_usd"):
        PressureConfig(budget_usd=-1.0)


def test_negative_model_cost_is_a_config_error():
    with pytest.raises(ValueError, match="model_costs"):
        PressureConfig(model_costs={"frontier": -1.0})


# --------------------------------------------------------------------------
# Policy layer
# --------------------------------------------------------------------------

def test_policy_accepts_both_modes():
    from iaiso.policy import _validate
    _validate({"version": "1", "enforcement_mode": "strict"})
    _validate({"version": "1", "enforcement_mode": "permissive"})


def test_policy_rejects_unknown_mode():
    from iaiso.policy import PolicyError, _validate
    with pytest.raises(PolicyError, match="enforcement_mode"):
        _validate({"version": "1", "enforcement_mode": "advisory"})


def test_policy_rejects_wrong_type():
    from iaiso.policy import PolicyError, _validate
    with pytest.raises(PolicyError, match="enforcement_mode"):
        _validate({"version": "1", "enforcement_mode": 1})
