package consent

import (
	"fmt"

	"github.com/golang-jwt/jwt/v5"
)

// IssuerOptions configures an Issuer.
type IssuerOptions struct {
	// SigningKey is the HS256 secret or the RS256 private key PEM.
	SigningKey []byte
	// Algorithm defaults to HS256.
	Algorithm Algorithm
	// Issuer is the `iss` claim. Defaults to "iaiso".
	Issuer string
	// DefaultTTLSeconds defaults to 3600.
	DefaultTTLSeconds int64
	// Clock defaults to SystemClock.
	Clock Clock
	// KeyAutoGenerated records that SigningKey was minted at boot rather
	// than supplied by the operator. Strict mode refuses this with HS256.
	KeyAutoGenerated bool
	// EnforcementMode is "permissive" (default) or "strict".
	EnforcementMode string
}

// Issuer mints signed consent tokens.
type Issuer struct {
	opts IssuerOptions
	clk  Clock
}

// NewIssuer validates the options and returns an Issuer.
//
// Under enforcement_mode: strict, an auto-generated HS256 signing key is a
// boot failure: nothing outside this process can verify what it signs, so
// the consent gate would authorise only itself.
func NewIssuer(opts IssuerOptions) (*Issuer, error) {
	if opts.Algorithm == "" {
		opts.Algorithm = HS256
	}
	if !opts.Algorithm.Valid() {
		return nil, fmt.Errorf("%w: %q", ErrUnsupportedAlgorithm, opts.Algorithm)
	}
	if opts.Issuer == "" {
		opts.Issuer = "iaiso"
	}
	if opts.DefaultTTLSeconds <= 0 {
		opts.DefaultTTLSeconds = 3600
	}
	if len(opts.SigningKey) == 0 {
		return nil, fmt.Errorf("%w: signing key is empty", ErrSigningFailed)
	}
	if opts.EnforcementMode == "strict" && opts.Algorithm == HS256 && opts.KeyAutoGenerated {
		return nil, fmt.Errorf(
			"iaiso: strict mode — consent algorithm is HS256 and the signing key was " +
				"auto-generated; no other party can verify these tokens. Supply a key, " +
				"switch to RS256, or set enforcement_mode: permissive")
	}
	clk := opts.Clock
	if clk == nil {
		clk = SystemClock()
	}
	return &Issuer{opts: opts, clk: clk}, nil
}

// IssueParams are the inputs to a single Issue call.
type IssueParams struct {
	Subject     string
	Scopes      []string
	ExecutionID string
	// TTLSeconds overrides IssuerOptions.DefaultTTLSeconds when > 0.
	TTLSeconds int64
	Metadata   map[string]any
}

// Issue mints and signs a consent token.
func (i *Issuer) Issue(p IssueParams) (*Scope, error) {
	now := i.clk()
	ttl := p.TTLSeconds
	if ttl <= 0 {
		ttl = i.opts.DefaultTTLSeconds
	}
	exp := now + ttl
	jti := generateJTI()

	scopes := p.Scopes
	if scopes == nil {
		scopes = []string{}
	}

	claims := Claims{
		Scopes:      scopes,
		ExecutionID: p.ExecutionID,
		Metadata:    p.Metadata,
		RegisteredClaims: jwt.RegisteredClaims{
			Issuer:    i.opts.Issuer,
			Subject:   p.Subject,
			IssuedAt:  jwt.NewNumericDate(unixTime(now)),
			ExpiresAt: jwt.NewNumericDate(unixTime(exp)),
			ID:        jti,
		},
	}

	var (
		method jwt.SigningMethod
		key    any
		err    error
	)
	switch i.opts.Algorithm {
	case HS256:
		method, key = jwt.SigningMethodHS256, i.opts.SigningKey
	case RS256:
		method = jwt.SigningMethodRS256
		key, err = parseRSAPrivateKey(i.opts.SigningKey)
		if err != nil {
			return nil, err
		}
	}

	signed, err := jwt.NewWithClaims(method, claims).SignedString(key)
	if err != nil {
		return nil, fmt.Errorf("%w: %v", ErrSigningFailed, err)
	}

	md := p.Metadata
	if md == nil {
		md = map[string]any{}
	}
	return &Scope{
		Token:       signed,
		Subject:     p.Subject,
		Scopes:      scopes,
		ExecutionID: p.ExecutionID,
		JTI:         jti,
		IssuedAt:    now,
		ExpiresAt:   exp,
		Metadata:    md,
	}, nil
}
