package consent

import (
	"errors"
	"fmt"

	"github.com/golang-jwt/jwt/v5"
)

// VerifierOptions configures a Verifier.
type VerifierOptions struct {
	// VerificationKey is the HS256 secret or the RS256 public key PEM.
	VerificationKey []byte
	// Algorithm defaults to HS256. Only this algorithm is accepted, so a
	// token whose header claims a different alg is rejected outright.
	Algorithm Algorithm
	// Issuer is the expected `iss`. Defaults to "iaiso".
	Issuer string
	// RevocationList is optional.
	RevocationList *RevocationList
	// LeewaySeconds tolerates clock skew on exp. Defaults to 5.
	LeewaySeconds int64
	// Clock defaults to SystemClock. Expiry is checked against this clock,
	// not against the process wallclock, so verification is deterministic.
	Clock Clock
	// KeyAutoGenerated and EnforcementMode mirror IssuerOptions.
	KeyAutoGenerated bool
	EnforcementMode  string
}

// Verifier validates signed consent tokens.
type Verifier struct {
	opts VerifierOptions
	clk  Clock
}

// NewVerifier validates the options and returns a Verifier.
func NewVerifier(opts VerifierOptions) (*Verifier, error) {
	if opts.Algorithm == "" {
		opts.Algorithm = HS256
	}
	if !opts.Algorithm.Valid() {
		return nil, fmt.Errorf("%w: %q", ErrUnsupportedAlgorithm, opts.Algorithm)
	}
	if opts.Issuer == "" {
		opts.Issuer = "iaiso"
	}
	if opts.LeewaySeconds <= 0 {
		opts.LeewaySeconds = 5
	}
	if len(opts.VerificationKey) == 0 {
		return nil, fmt.Errorf("%w: verification key is empty", ErrInvalidToken)
	}
	if opts.EnforcementMode == "strict" && opts.Algorithm == HS256 && opts.KeyAutoGenerated {
		return nil, fmt.Errorf(
			"iaiso: strict mode — consent algorithm is HS256 and the verification key was " +
				"auto-generated; the verifier holds the signing secret. Supply a key, " +
				"switch to RS256, or set enforcement_mode: permissive")
	}
	clk := opts.Clock
	if clk == nil {
		clk = SystemClock()
	}
	return &Verifier{opts: opts, clk: clk}, nil
}

// Verify checks signature, issuer, required claims, expiry, revocation and
// execution binding, in that order.
//
// executionID, when non-empty, must match a token that carries an
// execution_id claim. A token bound to another execution is invalid, not
// merely insufficient: it was minted for someone else's run.
func (v *Verifier) Verify(token string, executionID string) (*Scope, error) {
	keyFunc := func(t *jwt.Token) (any, error) {
		if t.Method.Alg() != string(v.opts.Algorithm) {
			return nil, fmt.Errorf("%w: unexpected signing method %q",
				ErrInvalidToken, t.Method.Alg())
		}
		switch v.opts.Algorithm {
		case HS256:
			return v.opts.VerificationKey, nil
		case RS256:
			return parseRSAPublicKey(v.opts.VerificationKey)
		}
		return nil, ErrUnsupportedAlgorithm
	}

	claims := &Claims{}
	// Expiry is validated manually below against the injected clock, so we
	// disable the library's wallclock-based expiry check here.
	parser := jwt.NewParser(
		jwt.WithValidMethods([]string{string(v.opts.Algorithm)}),
		jwt.WithIssuer(v.opts.Issuer),
		jwt.WithExpirationRequired(),
		jwt.WithoutClaimsValidation(),
	)
	parsed, err := parser.ParseWithClaims(token, claims, keyFunc)
	if err != nil {
		if errors.Is(err, jwt.ErrTokenExpired) {
			return nil, ErrExpiredToken
		}
		return nil, fmt.Errorf("%w: %v", ErrInvalidToken, err)
	}
	if !parsed.Valid {
		return nil, fmt.Errorf("%w: signature verification failed", ErrInvalidToken)
	}

	// WithoutClaimsValidation disables the issuer check too, so do it here.
	if claims.Issuer != v.opts.Issuer {
		return nil, fmt.Errorf("%w: issuer %q, expected %q",
			ErrInvalidToken, claims.Issuer, v.opts.Issuer)
	}
	if claims.Subject == "" {
		return nil, fmt.Errorf("%w: missing required claim: sub", ErrInvalidToken)
	}
	if claims.IssuedAt == nil {
		return nil, fmt.Errorf("%w: missing required claim: iat", ErrInvalidToken)
	}
	if claims.ExpiresAt == nil {
		return nil, fmt.Errorf("%w: missing required claim: exp", ErrInvalidToken)
	}
	if claims.ID == "" {
		return nil, fmt.Errorf("%w: missing required claim: jti", ErrInvalidToken)
	}

	exp := claims.ExpiresAt.Unix()
	if exp+v.opts.LeewaySeconds < v.clk() {
		return nil, ErrExpiredToken
	}

	if v.opts.RevocationList != nil && v.opts.RevocationList.IsRevoked(claims.ID) {
		return nil, fmt.Errorf("%w: jti=%s", ErrRevokedToken, claims.ID)
	}

	if executionID != "" && claims.ExecutionID != "" && executionID != claims.ExecutionID {
		return nil, fmt.Errorf("%w: token bound to %q, requested %q",
			ErrInvalidToken, claims.ExecutionID, executionID)
	}

	md := claims.Metadata
	if md == nil {
		md = map[string]any{}
	}
	scopes := claims.Scopes
	if scopes == nil {
		scopes = []string{}
	}
	return &Scope{
		Token:       token,
		Subject:     claims.Subject,
		Scopes:      scopes,
		ExecutionID: claims.ExecutionID,
		JTI:         claims.ID,
		IssuedAt:    claims.IssuedAt.Unix(),
		ExpiresAt:   exp,
		Metadata:    md,
	}, nil
}

// RequireScope verifies token and then asserts it grants requested. This is
// the one-call form for gating an expensive operation.
func (v *Verifier) RequireScope(token, executionID, requested string) (*Scope, error) {
	scope, err := v.Verify(token, executionID)
	if err != nil {
		return nil, err
	}
	if err := scope.Require(requested); err != nil {
		return nil, err
	}
	return scope, nil
}
